### ISSUE TITLE
Insert debug info does'nt work on release builds

### ISSUE THREAD

**Issue by JensBorrisholt** [MahdiSafsafi/DebugEngine#5]
Insert debug info does'nt work on release builds. I've tried both the DD tool and the ConvertMapToSMap function in the project. It fails on both 32 and 64 bit. 

## How to reproduce:

1) Build the demo as release. 
2) press "Insert debug info" button. 

## Or use the DD tool

1) Build the demo as release. 
2) Call the DD tool:   dd -c "./Win64/Release/ExceptionTest.map"

**Comment by MahdiSafsafi** [comment]
Hi JensBorrisholt,
You got this issue because your project (release mode) wasn't configured correctly !
Here is how to configure DebugEngine:
-   Open your project/Demo, and make sure that "Release configuration" or "All configurations" is set in "**Target**" property.
-   Then select ```Project->Options->Compiling->Debugging``` and make sure that “Debug information” option points to “Debug information”
-   Select ```Project->Options->Delphi Compiler->Linking``` and make the “Map file” option points to “Detailed” and press the Ok button.

Now, both DD tools and the Demo should work correctly.
For more information, check out the wiki pages.

Please give a feed-back so I can close the issue.

Mahdi.

**Comment by JensBorrisholt** [comment]
Hello

Ok. somehow I missed that. Now your demo project is working. I'm moving you code to my own project, and there I can not get it to work. I've create a minimum example, to reproduce the problem. 

1) download http://borrisholt.dk/GitHub/ExceptionTest.7z
2) Compile it as 64 bit release.
3) run DD.bat, placed alon with the dpr file. 

Jens Borrisholt

**Comment by MahdiSafsafi** [comment]
Hi again,
It doesn't work because you didn't enable debug info for your (release mode) !

![exception](https://cloud.githubusercontent.com/assets/12677682/25441956/fcbd7dc0-2aa3-11e7-8542-4672c3f58bc4.PNG)

Set "Debug information" property to "Debug information" and press Ok button : 

![exception_solution](https://cloud.githubusercontent.com/assets/12677682/25442004/1f88f14a-2aa4-11e7-83ea-e722822cd463.PNG)

Now it should work like a charm !

Mahdi.

**Comment by JensBorrisholt** [comment]
Thankyou verymuch for you help. Ive overlooked that even thought I enable debug information on "all configurations" then I have to set it on release mode.  

And yes ofcause it works :)
