### ISSUE TITLE
AV in procedure TCallTrace32.RemoveSealedCalls;

### ISSUE THREAD

**Issue by JensBorrisholt** [MahdiSafsafi/DebugEngine#7]
unit DebugEngine.Trace;

procedure TCallTrace32.RemoveSealedCalls; can raise an AV in sub function TargetExists if PItem^.Info.ProcedureAddress is nil then (PPointer(PItem^.Info.ProcedureAddress)^ = Address) raises an AV

I suggest the following change in order for fixing it : change function TStackItem.IsValid: Boolean; to the following implementation:

function TStackItem.IsValid: Boolean;
begin
  Result := (Rank <> 0) and (Info.ProcedureAddress <> nil);
end;

**Comment by MahdiSafsafi** [comment]
Thank you man ! You helped me a lot when you reported all issues you got !

Yeah it makes sense ! But editing ``` TStackItem.IsValid``` is useless since item can be valid even if ```Info.ProcedureAddress = nil```. ```Info.ProcedureAddress``` is a debug information ! Thus not all functions have debug info (eg: WinApi functions).

The best ways to handle this issue is to change this statement
``` if (PItem^.IsValid) and (not PItem^.OutOfRange) and (PPointer(PItem^.Info.ProcedureAddress)^ = Address) then```
**TO** 
```   if (PItem^.IsValid) and (not PItem^.OutOfRange) and (Assigned(PItem^.Info.ProcedureAddress)) and (PPointer(PItem^.Info.ProcedureAddress)^ = Address) then```
